diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="C:/Users/Vladimir.Bugaev/AppData/Local/Programs/Microsoft VS Code/bin/code" --wait
user.name=vladimir_bugaev
user.email=Vladimir.Bugaev@waveaccess.global
merge.guitool=kdiff3
pull.rebase=false
fetch.prune=false
rebase.autostash=false
mergetool.kdiff3.cmd="" "$BASE" "$LOCAL" "$REMOTE" -o "$MERGED"
mergetool.kdiff3.path=C:/Program Files/KDiff3/kdiff3.exe
diff.guitool=kdiff3
difftool.kdiff3.path=C:/Program Files/KDiff3/kdiff3.exe
difftool.kdiff3.cmd="C:/Program Files/KDiff3/kdiff3.exe" "$LOCAL" "$REMOTE"
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hookspath=.husky
submodule.active=.
remote.origin.url=https://github.com/marinerbob/ng-games-db.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
